name: Deploy CI
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN.PERSONAL_ACCESS_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.GITHUB_TOKEN.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.GITHUB_TOKEN.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.GITHUB_TOKEN.VERCEL_PROJECT_ID }}
