name: Lint check

on: pull_request

jobs:
  build-test:
    name: Next Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install -g pnpm
      - run: pnpm

      - name: Run Lint
        run: pnpm lint
